version: "3.9"

services:
  strapi:
    container_name: strapi
    image: strapi/strapi
    environment:
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_NAME
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE_CLIENT=postgres
      - NGINX_URL=api.example.com
    expose:
      - ${PORT:-1337}
    volumes:
      - .:/srv/app
    depends_on:
      - db
    command: "strapi start"

  webhooks:
    container_name: webhooks
    image: node:lts-alpine
    env_file: .env
    working_dir: /usr/app
    expose:
      - 1338
    volumes:
      - ./webhooks:/usr/app
    depends_on:
      - strapi
    command: "node content-update-webhook.js"

  db:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:?err}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?err}
      POSTGRES_DB: ${DATABASE_NAME:?err}
