version: "3.9"
services:

  strapi:
    restart: always
    expose:
      - ${PORT:-1337}
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:mainline-alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST
      - NGINX_PORT=80
      - STRAPI_SERVICE_NAME=strapi
      - STRAPI_PORT=${PORT:-1337}
    volumes:
      - ./data/nginx/templates:/etc/nginx/templates:ro
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
    depends_on:
      - strapi
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt:rw
      - ./data/certbot/www:/var/www/certbot:rw
    # command: delete --cert-name ${NGINX_HOST}
    # command: certonly --webroot --webroot-path=/var/www/certbot --email ${EMAIL_DEFAULT_ADMIN} --agree-tos --no-eff-email -d ${NGINX_HOST}
    # command: certonly --webroot --webroot-path=/var/www/certbot --email ${EMAIL_DEFAULT_ADMIN} --agree-tos --no-eff-email --staging -d ${NGINX_HOST}
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
      - strapi
