version: "3"

services:
  strapi:
    container_name: strapi
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    ports:
      - 1337:1337
    volumes:
      - .:/srv/app
    depends_on:
      - db
    command: "strapi start"

  webhooks:
    container_name: webhooks
    image: node:lts-alpine
    env_file: .env
    working_dir: /usr/app
    ports:
      - 1338:1338
    volumes:
      - ./webhooks:/usr/app
    depends_on:
      - strapi
    command: "node content-update-webhook.js"

  db:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
