version: "3.9"
services:
  strapi:
    stdin_open: true
    tty: true
    ports:
      - 1337:${PORT:-1337}
    command: "strapi develop"

  db:
    stdin_open: true
    tty: true
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
